import React, { useState } from 'react';
import { Brain, Cpu, Database, Layout, Mic, Zap, ChevronRight } from 'lucide-react';

const FeaturesDemo = () => {
  const [demoLevel, setDemoLevel] = useState('Beginner');

  const adaptiveContent = {
    Beginner: "A 'Variable' is like a labeled box where you store information, such as a number or a name, to use later in your program.",
    Intermediate: "Variables are named memory locations that hold data. You must declare their type (like int or string) so the computer knows how much space to reserve.",
    Advanced: "A variable is an abstraction of a memory address. It is defined by a scope, a lifetime, and a data type that determines its binary representation."
  };

  return (
    // 1. Changed py-20 to py-12 to reduce vertical space if needed
    // 2. Used w-full to ensure the section spans the entire width
    <section className="w-full py-12 bg-slate-50 dark:bg-slate-950 transition-colors duration-300">
      
      {/* 3. Replaced 'container mx-auto' with 'px-4 md:px-8 lg:px-12' for a wider fluid layout */}
      <div className="max-w-[100%] px-4 md:px-10 lg:px-16">
        
        {/* 1. Interactive Adaptive Demo */}
        {/* 4. Changed 'max-w-4xl' to 'max-w-6xl' or 'w-full' for a wider card */}
        <div className="max-w-7xl mx-auto bg-white dark:bg-slate-900 rounded-3xl shadow-xl overflow-hidden mb-20 border border-slate-100 dark:border-slate-800 transition-all duration-300">
          <div className="flex flex-col md:flex-row min-h-[400px]">
            <div className="p-8 md:w-1/4 bg-slate-900 dark:bg-slate-950 text-white transition-colors duration-300">
              <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                <Brain className="text-blue-400" /> Adaptive Logic
              </h3>
              <p className="text-slate-400 text-sm mb-6">
                Select a level to see how our AI reformulates the same concept in real-time.
              </p>
              <div className="space-y-3">
                {['Beginner', 'Intermediate', 'Advanced'].map((lvl) => (
                  <button
                    key={lvl}
                    onClick={() => setDemoLevel(lvl)}
                    className={`w-full text-left px-4 py-3 rounded-xl transition-all font-medium flex justify-between items-center ${
                      demoLevel === lvl ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700 dark:bg-slate-900 dark:hover:bg-slate-800'
                    }`}
                  >
                    {lvl}
                    {demoLevel === lvl && <ChevronRight size={18} />}
                  </button>
                ))}
              </div>
            </div>
            
            <div className="p-10 md:w-3/4 flex flex-col justify-center bg-blue-50/30 dark:bg-slate-800/50 transition-colors duration-300">
              <span className="text-blue-600 dark:text-blue-400 font-bold text-sm uppercase tracking-widest mb-2">Live Concept: Variables</span>
              {/* text-3xl or 4xl makes better use of the wider space */}
              <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-6 italic transition-colors duration-300">
                "{adaptiveContent[demoLevel]}"
              </h2>
              <div className="flex items-center gap-4 text-slate-500 dark:text-slate-400 text-sm">
                <div className="flex -space-x-2">
                  <div className="w-10 h-10 rounded-full bg-blue-500 border-2 border-white dark:border-slate-700 flex items-center justify-center text-white text-xs font-bold">AI</div>
                </div>
                <span className="text-lg">Generated by Gemini 1.5 Flash based on <strong>{demoLevel}</strong> proficiency.</span>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
};

export default FeaturesDemo;